export const NewProductData = [
  {
    id: "c1",
    typeProduct: "vest",
    imageProduct: ["", "assets/image/image_home/bst_moi1.png"],
    name_product: "ÁO VEST GHI KẺ LH69",
    price_product: "2,950,000₫",
    isSale: false,
    discount_sale: "null",
    initialPrice: "null",
  },
  {
    id: "c2",
    typeProduct: "vest",
    imageProduct: ["", "assets/image/image_home/bst_moi2.jpg"],
    name_product: "ÁO VEST GHI KẺ LH69",
    price_product: "2,900,000₫",
    isSale: false,
    discount_sale: "null",
    initialPrice: "null",
  },
  {
    id: "c3",
    typeProduct: "vest",
    imageProduct: ["", "assets/image/image_home/bst_moi3.jpg"],
    name_product: "ÁO VEST KẺ XANH 263",
    price_product: "2,950,000₫",
    isSale: false,
    discount_sale: "null",
    initialPrice: "null",
  },
  {
    id: "c4",
    typeProduct: "vest",
    imageProduct: ["", "assets/image/image_home/bst_moi4.jpg"],
    name_product: "ÁO VEST BE AV256",
    price_product: "2,950,000₫",
    isSale: false,
    discount_sale: "null",
    initialPrice: "null",
  },
];
export const HotProductData = [
  {
    id: "c10",
    typeProduct: "vest",
    imageProduct: ["", "assets/image/image_home/san_pham_ban_chay_home1.jpg"],
    name_product: "ÁO VEST XANH LH73",
    price_product: "2,950,000₫",
    isSale: false,
    discount_sale: "null",
    initialPrice: "null",
  },
  {
    id: "c7",
    typeProduct: "vest",
    imageProduct: ["", "assets/image/image_home/san_pham_ban_chay_home2.jpg"],
    name_product: "ÁO VEST XANH KẺ AVLH50",
    price_product: "2,950,000₫",
    isSale: false,
    discount_sale: "null",
    initialPrice: "null",
  },

  {
    id: "c28",
    typeProduct: "vest",
    imageProduct: ["", "assets/image/image_home/san_pham_ban_chay_home3.jpg"],
    name_product: " ÁO VEST XANH KẺ LH63 ",
    price_product: "2,950,000₫",
    isSale: false,
    discount_sale: "null",
    initialPrice: "null",
  },
  {
    id: "c15",
    typeProduct: "vest",
    imageProduct: ["", "assets/image/image_home/san_pham_ban_chay_home4.jpg"],
    name_product: "ÁO VEST XANH AV246",
    price_product: "2,950,000₫",
    isSale: false,
    discount_sale: "null",
    initialPrice: "null",
  },
];
export const SaleProductData = [
  {
    id: "c26",
    typeProduct: "vest",
    imageProduct: ["", "assets/image/image_home/san_pham_khuyen_mai_home1.png"],
    name_product: "ÁO VEST ĐEN SỌC 286",
    price_product: "2,700,000₫",
    isSale: true,
    discount_sale: "-10%",
    initialPrice: "3,000,000₫",
  },

  {
    id: "c25",
    typeProduct: "vest",
    imageProduct: ["", "assets/image/image_home/san_pham_khuyen_mai_home2.png"],
    name_product: " ÁO VEST GHI KẺ LH67-B",
    price_product: "2,700,000₫",
    isSale: true,
    discount_sale: "-10%",
    initialPrice: "3,000,000₫",
  },

  {
    id: "c6",
    typeProduct: "vest",
    imageProduct: ["", "assets/image/image_home/san_pham_khuyen_mai_home3.png"],
    name_product: "ÁO VEST XANH KẺ LH64",
    price_product: "2,700,000₫",
    isSale: true,
    discount_sale: "-10%",
    initialPrice: "3,000,000₫",
  },
  {
    id: "c27",
    typeProduct: "vest",
    imageProduct: ["", "assets/image/image_home/san_pham_khuyen_mai_home4.png"],
    name_product: "ÁO VEST XANH TT KẺ 245",
    price_product: "2,700,000₫",
    isSale: true,
    discount_sale: "-10%",
    initialPrice: "3,000,000₫",
  },
];
